# Generated by Django 3.0.8 on 2020-08-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0002_auto_20200819_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='grade',
            field=models.IntegerField(null=True),
        ),
    ]
