# Generated by Django 3.0.8 on 2020-09-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0004_score_totalattempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='averagescore',
            field=models.IntegerField(null=True),
        ),
    ]
